---
name: Build CI
on:
  - push
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017
        options: --name=mongodb
    env:
      MONGODB_URL: mongodb://localhost:27017/acebook_test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Run lint and unit tests
        run: |
          npm run lint
          npm run test:unit
      - name: Run integration tests
        uses: cypress-io/github-action@v6
        with:
          config-file: cypress.config.js
          start: npm run start:ci

  deploy:
    # If we're running on the main branch (not a PR)
    if: github.ref == 'refs/heads/main'
    # And no other deploy jobs are running
    needs: build

    concurrency: production

    runs-on: ubuntu-latest

    env:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      BALLOON_INSTANCE_IP_1: ${{ vars.BALLOON_INSTANCE_IP_1 }}

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Call a Bash Script to transfer files to servers  # Execute a Bash script.
        run: |
          chmod +x scripts/deploy-to-instance.sh  
          ./scripts/deploy-to-instance.sh 

